language: generic
sudo: false
addons:
  apt:
    packages:
    - git
    - build-essential
    - curl
script:
- BUILD_HOME="$TRAVIS_BUILD_DIR" DEPLOY_TO="$TRAVIS_BUILD_DIR/deploy/$TRAVIS_REPO_SLUG/$TRAVIS_BRANCH" ./build.sh
deploy:
  skip_cleanup: true
  provider: s3
  bucket: aptible-cadvisor
  acl: private
  local_dir: deploy
  access_key_id:
    secure: pllWLnJMzyWyzmHhKUH6tqByxKnETzpZuR2j03EJTf9wLQtkeGHVHB1scQeaLGrIG6+yU2sBKBws/BOfTNHF+Cenfbvl6LEfWm2y36MUXnUcCKhwjNwMk0v0Yus9QLPQEpJV8WfXm3ASPvbt6kdIspFP1WMaCdXjdxzaGKWA6SbIH3qjlcj5pcfvkPFl8ROnN83Oe2lK8UswCa1S5WKoCzsrSoVr5A6e9XWl8Ga2ZVgBkhC5GT7KZshxQfe1tbF8VylQDWU3jmYOn8xjSnE8dV9qhdRKJfEP3lUWaBcm7qPzaL4wVvqOIHLX2/HBIxnJUvrZcYL7aOmek10Dh4ETlIqmbKBR8mMP6bP3rFaZ6K96yiKnJXukKb1cG7YXtOIBWCPX2Yf5VOt0Zor2uW2UYDeAnoNZ0VyKnMJ5VuitnO1SXIP9KXf0YYyGpuP6ppVDXRnCDJwmxnzDheTK+Z1ImNk2xxOaYp04OlFa3L9u7ks8V56Hwo68lCvxCgBKyqsvXTClDV6RtVicNQKZnGiFHJvio3RQ7187voPR8MC94KmJiro0UkJjsRMiKfCVk5Nuopilm58v704B5InMKCVtChLwLdNbrHqqT6qZyIRRkQFa5YtqIgv52xb50neFNj60r5fG5CEf8VdmRerSKcWuVIKwle6V6Nb+uYpQI7o5K/A=
  secret_access_key:
    secure: BYixtZcWCvRyHuZ6j88qMS7P/Jk1kA9q0kjlBw4ry6x3pBs5i5X5gz0XGrgjNnSTqlBffDuD1X6x6sPS9OKogdXDgmZkAw652MgdKh5M0SRqn8Ug6xKj0eoOejwqR3quyD4V+VATLR48ElS/BzWrjKIUFTYmH87FH2qr5LU7saGelBz7tJjjtJkp9D2vBiEi30FfTS7ycCBT6wtPiayewExI4xHLLd5tMrjXy/8h8b+wgqnQFDlZKhQi/S2OPFLthw+HhxZugFScA9ir4F6oEqgFmNsXcxwPfKyqKNETp/raP/2IlxM0dyi0jFa8gDrFYQCue9UCywZpgvlHXq9M9bUiGHupFjGJQNBb9njDRZTtYpbN0TfIS+vteigcxTFQdcBn6bl+I9ZRJKtFTImvRdmNMg0oOwa9rkhuyPR0a1R/phiIsQprobLPpTrXDgMtshlzvDo0TTokTE1IXGBs+x8mtNnnTu/4xuNkBDmGVNalUN/nd8MssnXVO2/2b/qVBziyfc5YEnSgjC0sAJXpBlyMYkod7HF5x685zwu7cpykE4aSoHu6TmTQf46gBj8bcM27BiUUIWhJtSjS6nOn8KVm7sQtPBjoB4sfLBgy/4xqt45pUGP3ACfecXcdvTkZ4jgSPSmhD1S+7EXKDOh0f9Dx/nckFhtekv3QvIEkThU=
